# Created by trellis-cli v0.9.2
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  valeravilks.ru:
    site_hosts:
    - canonical: valeravilks.test
      redirects:
      - www.valeravilks.test
    local_path: ../site
    admin_email: admin@valeravilks.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
